ALTER TABLE "BotSettings"
ADD COLUMN IF NOT EXISTS "fixedRoeEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "fixedRoeTpPercent" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "fixedRoeSlPercent" DOUBLE PRECISION NOT NULL DEFAULT 20;
